### ISSUE TITLE
Develop the "Index.cshtml" under views "Home" folder

### ISSUE THREAD

**Issue by kopilkaiser** [DMU-CTEC2902-1920/ProCoders#1]
### Need development on the Home page(Index.cshtml, Home)

Hey Asim. Can you look on to the "Index.cshtml" under the "Home" folder and design the content in the page. Please reply back if you have been notified with the issue

**Comment by Syed-Cyber** [comment]
Yes I will start working on it.

**Comment by kopilkaiser** [comment]
Added completion date in Milestone
