### ISSUE TITLE
Development for "About US" page under Home folder in "Views"

### ISSUE THREAD

**Issue by kopilkaiser** [DMU-CTEC2902-1920/ProCoders#3]
hey Anas. Can you start designing the "About US" page? I would like you to start working as soon as possible.

**Comment by AnasAli20** [comment]
Ok, I will try my best to develop the "About us" before the deadline.
Thank You

**Comment by AnasAli20** [comment]
Hello Kopil,

I have completed the About us page alongside with my documentation.
Thank You

**Comment by AnasAli20** [comment]
Please have a look at my developed page is that ok or not, I will be waiting for your reply. Please let me know about further development.
