### ISSUE TITLE
Develop "Home" , "Show story" , "Create story page"

### ISSUE THREAD

**Issue by AnasAli20** [DMU-CTEC2902-1920/ProCoders#4]
Dear Kopil Kaiser, can you please develop the "Home", "Show story", "Create story page" .
Thank You

**Comment by kopilkaiser** [comment]
Hey Anas. I have already developed the three pages you have mentioned. Please kindly look on the work and give me feedback on the work. I have provided link of the commit to my workings. Commit to the work: https://github.com/DMU-CTEC2902-1920/ProCoders/commit/1d7b33ac651f0eac5c8920dc7674c9504b5dfd57

**Comment by AnasAli20** [comment]
Hello Kopil, I have looked up on you work. Great job indeed.
Thank you very much
